//go:build tile57

package server

import (
	"net/http"
	"strconv"
	"strings"

	tile57 "github.com/beetlebugorg/chartplotter-native/bindings/go"
)

// serveTile57Style returns a complete MapLibre style document generated by the
// native tile57 engine (tile57_style_template + tile57_build_style over the S-52
// colortables baked into libtile57), so the style itself — not just the tiles and
// symbology assets — comes from the engine. Query params (all optional):
//
//	scheme  day|dusk|night            (default day)
//	tiles   chart {z}/{x}/{y} URL     (default <origin>/tiles/tile57/{z}/{x}/{y}.mvt)
//	sprite  sprite base URL           (default <origin>/sprite)
//	glyphs  glyphs URL                (default <origin>/glyphs/{fontstack}/{range}.pbf)
//	bands   CSV of band ranks to show (default all)
//
// CORS-open like the tile + asset routes so a static-hosted client can fetch it.
func (s *Server) serveTile57Style(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Access-Control-Allow-Origin", "*")
	if r.Method != http.MethodGet {
		apiErr(w, http.StatusMethodNotAllowed, "GET only")
		return
	}
	q := r.URL.Query()
	scheme := tile57.SchemeFromString(q.Get("scheme"))
	base := requestOrigin(r)
	tiles := orDefault(q.Get("tiles"), base+"/tiles/tile57/{z}/{x}/{y}.mvt")
	sprite := orDefault(q.Get("sprite"), base+"/sprite")
	glyphs := orDefault(q.Get("glyphs"), base+"/glyphs/{fontstack}/{range}.pbf")

	m := tile57.MarinerDefaults()
	m.Scheme = scheme

	// SCAMIN buckets: feed build_style the set's SCAMIN manifest + a reference
	// latitude so it emits per-value native-minzoom bucket layers (matching the
	// offline bundle style). Default to the live "tile57" set; ?set picks another,
	// ?scamin / ?lat override. nil manifest ⇒ no buckets (back-compat).
	scamin := parseBands(q.Get("scamin"))
	lat := 0.0
	var maxZoom uint32 // 0 ⇒ engine default; the set's real top zoom otherwise
	if src, ok := s.lookupSet(orDefault(q.Get("set"), "tile57")); ok {
		meta := src.Meta()
		maxZoom = uint32(meta.MaxZoom) // live ENC = z18 (berthing); don't clamp to the engine's z16 default
		if len(scamin) == 0 {
			scamin = make([]int32, len(meta.Scamin))
			for i, v := range meta.Scamin {
				scamin[i] = int32(v)
			}
		}
		lat = (meta.S + meta.N) / 2 // bounds-centre latitude for the scale→zoom map
	}
	if v := q.Get("lat"); v != "" {
		if f, err := strconv.ParseFloat(v, 64); err == nil {
			lat = f
		}
	}

	// Generate the style with the chart source's maxzoom pinned to the set's real top
	// zoom. The convenience tile57.Style would clamp the template to the engine's z16
	// default and drop the finest (berthing) band's z17–18 detail; MapLibre overzooms
	// above maxzoom for free, so there's no reason to bake that ceiling in below 18.
	ct, err := tile57.ColortablesDefault()
	if err != nil {
		apiErr(w, http.StatusInternalServerError, err.Error())
		return
	}
	tmpl, err := tile57.StyleTemplate(scheme, tiles, sprite, glyphs, 0, maxZoom)
	if err != nil {
		apiErr(w, http.StatusInternalServerError, err.Error())
		return
	}
	style, err := tile57.BuildStyle(tmpl, m, ct, parseBands(q.Get("bands")), scamin, lat)
	if err != nil {
		apiErr(w, http.StatusInternalServerError, err.Error())
		return
	}
	w.Header().Set("Content-Type", jsonCT)
	w.Header().Set("Cache-Control", "no-cache")
	w.Write(style)
}

func orDefault(v, def string) string {
	if v == "" {
		return def
	}
	return v
}

// requestOrigin reconstructs the scheme://host the client reached us on, for the
// absolute URLs MapLibre needs in the style document.
func requestOrigin(r *http.Request) string {
	scheme := "http"
	if r.TLS != nil {
		scheme = "https"
	}
	return scheme + "://" + r.Host
}

// parseBands parses a CSV of band ranks ("0,1,2") into a slice; nil for "" (all).
func parseBands(csv string) []int32 {
	if csv == "" {
		return nil
	}
	var out []int32
	for _, p := range strings.Split(csv, ",") {
		if n, err := strconv.Atoi(strings.TrimSpace(p)); err == nil {
			out = append(out, int32(n))
		}
	}
	return out
}
