package assets

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/beetlebugorg/chartplotter-go/pkg/s52"
)

// Emit writes the generated S-52 asset files into dir, returning the list of
// files written. colortables.json is generated from the PresLib; the
// linestyles.json dash data and the sprite/pattern PNG atlases are generated by
// the (separate) atlas builder once wired.
func Emit(lib *s52.Library, dir string) ([]string, error) {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return nil, err
	}
	var written []string

	ct, err := ColorTablesJSON(lib)
	if err != nil {
		return nil, fmt.Errorf("colortables: %w", err)
	}
	p := filepath.Join(dir, "colortables.json")
	if err := os.WriteFile(p, ct, 0o644); err != nil {
		return nil, err
	}
	written = append(written, p)

	return written, nil
}
