package main

import (
	_ "embed"
	"runtime"

	"fyne.io/systray"
)

// Placeholder compass glyph generated by gen_icons.go (`go generate ./cmd/dock`);
// swap the PNG/ICO pairs for an OpenBridge asset without touching this file.
// Windows tray icons must be ICO; the other platforms take PNG. On macOS the
// PNGs are template images (monochrome + alpha) so the menu bar recolours them.
//
//go:generate go run gen_icons.go

//go:embed icon.png
var iconPNG []byte

//go:embed icon_error.png
var iconErrorPNG []byte

//go:embed icon.ico
var iconICO []byte

//go:embed icon_error.ico
var iconErrorICO []byte

// setTrayIcon applies the normal or error-badged glyph. SetTemplateIcon uses
// the first argument on macOS (template rendering) and the second elsewhere.
func setTrayIcon(errState bool) {
	png, ico := iconPNG, iconICO
	if errState {
		png, ico = iconErrorPNG, iconErrorICO
	}
	regular := png
	if runtime.GOOS == "windows" {
		regular = ico
	}
	systray.SetTemplateIcon(png, regular)
}
