// Command portrayal-inventory cross-references the symbology our embedded S-52
// DAI presentation library defines against what the IHO S-101 Portrayal
// Catalogue provides, and emits a coverage matrix. It is the Phase 1 tool of
// the S-101 backport (see specs/s101-portrayal-backport.md): it tells us
// exactly which symbols / line styles / area fills / colours / object classes
// have an S-101 equivalent and which are gaps that need a placeholder or our
// own catalogue entry.
//
// Usage:
//
//	go run ./cmd/portrayal-inventory --catalog /path/to/S-101_Portrayal-Catalogue/PortrayalCatalog [--out specs/s101-coverage-matrix.md]
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/beetlebugorg/chartplotter/pkg/s52"
	"github.com/beetlebugorg/chartplotter/pkg/s52/preslib"
)

func main() {
	catalog := flag.String("catalog", "/home/jcollins/Projects/s101-portrayal-catalogue/PortrayalCatalog", "path to S-101 PortrayalCatalog directory")
	out := flag.String("out", "", "write markdown matrix here (default: stdout)")
	flag.Parse()

	lib, err := s52.LoadLibraryFromBytes(preslib.DAI)
	if err != nil {
		fatal("load DAI: %v", err)
	}

	// --- our side (S-52 DAI) ---
	daiSymbols := set(lib.ListSymbols())
	daiLines := set(lib.ListLineStyles())
	daiPatterns := set(lib.ListPatterns())
	daiColors := set(lib.ListColors(s52.ColorSchemeDay))
	daiClasses := set(lib.ListObjectClasses())

	// --- S-101 side ---
	s101Symbols := basenames(*catalog, "Symbols", ".svg")
	s101Lines := basenames(*catalog, "LineStyles", ".xml")
	s101Fills := basenames(*catalog, "AreaFills", ".xml")
	s101Rules := basenames(*catalog, "Rules", ".lua")
	s101Colors := colorTokens(filepath.Join(*catalog, "ColorProfiles", "colorProfile.xml"))

	var b strings.Builder
	fmt.Fprintf(&b, "# S-52 DAI ↔ S-101 coverage matrix\n\n")
	fmt.Fprintf(&b, "_Generated by `cmd/portrayal-inventory`. Phase 1 of specs/s101-portrayal-backport.md._\n\n")
	fmt.Fprintf(&b, "Counts — DAI: %d symbols, %d line styles, %d patterns, %d colours, %d object classes. "+
		"S-101: %d symbols, %d line styles, %d area fills, %d colours, %d rules.\n\n",
		len(daiSymbols), len(daiLines), len(daiPatterns), len(daiColors), len(daiClasses),
		len(s101Symbols), len(s101Lines), len(s101Fills), len(s101Colors), len(s101Rules))

	// Symbols: which DAI symbol IDs exist as an S-101 SVG of the same name.
	section(&b, "Symbols", "DAI symbol", "S-101 SVG", daiSymbols, s101Symbols)
	section(&b, "Line styles", "DAI line style", "S-101 LineStyle XML", daiLines, s101Lines)
	// Patterns (DAI) ↔ Area fills (S-101) — same family, compare by id.
	section(&b, "Patterns / area fills", "DAI pattern", "S-101 AreaFill XML", daiPatterns, s101Fills)
	section(&b, "Colours", "DAI colour token", "S-101 colour token", daiColors, s101Colors)

	// Object classes: our LUPT keys are S-57 6-char acronyms; S-101 rules are
	// camelCase feature-class codes. They are NOT directly comparable by name —
	// this needs the S-57→S-101 bridge (Workstream E). We list both raw sets so
	// the size of that mapping job is visible.
	fmt.Fprintf(&b, "## Object classes (needs S-57→S-101 bridge — names not directly comparable)\n\n")
	fmt.Fprintf(&b, "- DAI LUPT object classes (S-57 acronyms): **%d**\n", len(daiClasses))
	fmt.Fprintf(&b, "- S-101 rule files (feature-class codes): **%d**\n\n", len(s101Rules))
	fmt.Fprintf(&b, "<details><summary>DAI object classes (%d)</summary>\n\n%s\n</details>\n\n", len(daiClasses), columns(keys(daiClasses)))
	fmt.Fprintf(&b, "<details><summary>S-101 rule codes (%d)</summary>\n\n%s\n</details>\n\n", len(s101Rules), columns(keys(s101Rules)))

	result := b.String()
	if *out == "" {
		fmt.Print(result)
		return
	}
	if err := os.WriteFile(*out, []byte(result), 0o644); err != nil {
		fatal("write %s: %v", *out, err)
	}
	fmt.Fprintf(os.Stderr, "wrote %s\n", *out)
}

// section emits a coverage block: how many of `ours` are covered by `theirs`,
// the missing ones (gaps needing placeholder/own entry), and items only in S-101.
func section(b *strings.Builder, title, ourLabel, theirLabel string, ours, theirs map[string]bool) {
	var covered, missing []string
	for id := range ours {
		if theirs[id] {
			covered = append(covered, id)
		} else {
			missing = append(missing, id)
		}
	}
	var extra []string
	for id := range theirs {
		if !ours[id] {
			extra = append(extra, id)
		}
	}
	sort.Strings(missing)
	sort.Strings(extra)

	fmt.Fprintf(b, "## %s\n\n", title)
	fmt.Fprintf(b, "- %s defs: **%d** — covered by %s: **%d** — **gaps: %d**\n",
		ourLabel, len(ours), theirLabel, len(covered), len(missing))
	fmt.Fprintf(b, "- %s items with no DAI equivalent: **%d**\n\n", theirLabel, len(extra))
	if len(missing) > 0 {
		fmt.Fprintf(b, "**Gaps (in DAI, missing from S-101 → placeholder / make our own):**\n\n%s\n\n", columns(missing))
	}
	if len(extra) > 0 {
		fmt.Fprintf(b, "<details><summary>Only in S-101 (%d)</summary>\n\n%s\n</details>\n\n", len(extra), columns(extra))
	}
}

func basenames(catalog, sub, ext string) map[string]bool {
	dir := filepath.Join(catalog, sub)
	entries, err := os.ReadDir(dir)
	if err != nil {
		fatal("read %s: %v", dir, err)
	}
	out := map[string]bool{}
	for _, e := range entries {
		n := e.Name()
		if strings.EqualFold(filepath.Ext(n), ext) {
			out[strings.TrimSuffix(n, filepath.Ext(n))] = true
		}
	}
	return out
}

var colorTokenRE = regexp.MustCompile(`<color\s+token="([^"]+)"`)

func colorTokens(path string) map[string]bool {
	data, err := os.ReadFile(path)
	if err != nil {
		fatal("read %s: %v", path, err)
	}
	out := map[string]bool{}
	for _, m := range colorTokenRE.FindAllSubmatch(data, -1) {
		out[string(m[1])] = true
	}
	return out
}

func set(ids []string) map[string]bool {
	out := make(map[string]bool, len(ids))
	for _, id := range ids {
		out[id] = true
	}
	return out
}

func keys(m map[string]bool) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

// columns formats ids into a fixed-width grid for compact, scannable output.
func columns(ids []string) string {
	if len(ids) == 0 {
		return "_(none)_"
	}
	const cols = 6
	var b strings.Builder
	b.WriteString("```\n")
	for i, id := range ids {
		fmt.Fprintf(&b, "%-12s", id)
		if (i+1)%cols == 0 {
			b.WriteString("\n")
		}
	}
	if len(ids)%cols != 0 {
		b.WriteString("\n")
	}
	b.WriteString("```")
	return b.String()
}

func fatal(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "portrayal-inventory: "+format+"\n", args...)
	os.Exit(1)
}
